# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'GNLocationManagerExample' do
pod 'CWLSynthesizeSingleton', '~> 1.0'
end

target 'GNLocationManagerExampleTests' do
pod 'CWLSynthesizeSingleton', '~> 1.0'
end

